### ISSUE TITLE
Where there any plans to add playbooks from Book 3?

### ISSUE THREAD

**Issue by Soundwavesghost** [AuthorX/Fellowship-for-Roll20#2]
If you need a copy I can DM you a copy of them as I just purchased them and would love to play the new Empire on roll20.

**Comment by AuthorX** [comment]
Hey, sorry for the long delay in replying, I haven't really looked at my repository in a long time until now. I have the new playbooks, but the character sheets are for the original, 1e release, and the whole sheet would need to be reviewed to adapt the changes in 2e. I may get started with that now that I'm working on sheets again and Book 4 is out, but it will probably be a long product if I do.
